#version: '3.8'
services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: chatting
      MYSQL_USER: chatting
      MYSQL_PASSWORD: chatting
      TZ: Asia/Seoul
    ports:
      - "3308:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    networks:
      - app-network



  mongodb:
    image: mongo:latest
    container_name: chatting
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: chatting
      MONGO_INITDB_ROOT_PASSWORD: chatting
      MONGO_INITDB_DATABASE: chatting
    volumes:
      - mongodb_data:/data/db
    #       초기화 스크립트가 필요한 경우 주석 해제
    #       - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command:
      - --auth
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:


